// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChYDdDILn7OG00G0EJ_j-nJaazyMZYm-Q',
    appId: '1:47200534772:web:8164e194093e0981f79ea1',
    messagingSenderId: '47200534772',
    projectId: 'myclinics-4477a',
    authDomain: 'myclinics-4477a.firebaseapp.com',
    storageBucket: 'myclinics-4477a.appspot.com',
    measurementId: 'G-06KQ20T2Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnkzuNRlUk4lOxvSNNt-yNQqQ5myqbxFg',
    appId: '1:47200534772:android:03c9fb19c37ca6f4f79ea1',
    messagingSenderId: '47200534772',
    projectId: 'myclinics-4477a',
    storageBucket: 'myclinics-4477a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzrL1IuCLewZEq4aUDfOxagtAYKDsB73M',
    appId: '1:47200534772:ios:4e253cd951abdea3f79ea1',
    messagingSenderId: '47200534772',
    projectId: 'myclinics-4477a',
    storageBucket: 'myclinics-4477a.appspot.com',
    androidClientId: '47200534772-4gifo2r1uhbcfgi46enbk617uge3qu46.apps.googleusercontent.com',
    iosClientId: '47200534772-5stcqe64oqjhd2vrv10ncm84d9jhinmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.myclinics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzrL1IuCLewZEq4aUDfOxagtAYKDsB73M',
    appId: '1:47200534772:ios:4e253cd951abdea3f79ea1',
    messagingSenderId: '47200534772',
    projectId: 'myclinics-4477a',
    storageBucket: 'myclinics-4477a.appspot.com',
    androidClientId: '47200534772-4gifo2r1uhbcfgi46enbk617uge3qu46.apps.googleusercontent.com',
    iosClientId: '47200534772-5stcqe64oqjhd2vrv10ncm84d9jhinmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.myclinics',
  );
}
